# Generated by Django 2.1.7 on 2019-02-19 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190218_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
