# Generated by Django 2.1.7 on 2019-02-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_store'),
        ('accounts', '0005_auto_20190221_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
