# Generated by Django 2.1.7 on 2019-02-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
