# Generated by Django 2.1.7 on 2019-02-20 04:04

from django.db import migrations, models
import django.db.models.deletion
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', places.fields.PlacesField(max_length=255)),
                ('is_draft', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('0', 'Deleted'), ('1', 'Available'), ('2', 'Sold')], default='1', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Store')),
            ],
        ),
    ]
