# Generated by Django 2.1.7 on 2019-02-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productalbum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
    ]
