# Generated by Django 2.1.7 on 2019-02-28 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_comment_favorite_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('can_publish_draft', 'Can publish a draft post'), ('can_make_available', 'Can make product available'), ('can_restock_item', 'Can restock item'))},
        ),
    ]
