# Generated by Django 2.1.7 on 2019-03-01 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_published_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
