# Generated by Django 2.1.7 on 2019-03-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190301_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('can_publish_draft', 'Can publish a draft post'), ('can_make_available', 'Can make product available'), ('can_restock_item', 'Can restock item'), ('can_mark_sold', 'Can mark as sold'))},
        ),
    ]
